# Generated by Django 4.2.21 on 2025-05-24 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, help_text='About/Bio section', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='experience_description',
            field=models.TextField(blank=True, help_text='Detailed experience description', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='languages',
            field=models.JSONField(blank=True, default=list, help_text='Array of languages spoken'),
        ),
        migrations.AddField(
            model_name='user',
            name='skills',
            field=models.JSONField(blank=True, default=list, help_text='Array of skills'),
        ),
        migrations.AddField(
            model_name='user',
            name='total_completed_jobs',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='total_reviews',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='years_of_experience',
            field=models.PositiveIntegerField(blank=True, help_text='Years of professional experience', null=True),
        ),
    ]
