# Generated by Django 4.2.21 on 2025-05-24 21:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_average_rating_user_bio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('job_type', models.CharField(choices=[('one-time', 'One-time'), ('recurring', 'Recurring'), ('urgent', 'Urgent')], default='one-time', max_length=20)),
                ('urgent', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('duration', models.CharField(blank=True, choices=[('under-1-hour', 'Under 1 hour'), ('1-2-hours', '1-2 hours'), ('2-4-hours', '2-4 hours'), ('4-8-hours', '4-8 hours'), ('full-day', 'Full day (8+ hours)'), ('multi-day', 'Multi-day project'), ('1-week', 'About 1 week'), ('ongoing', 'Ongoing')], max_length=20, null=True)),
                ('flexible_schedule', models.BooleanField(default=False)),
                ('payment_type', models.CharField(choices=[('fixed', 'Fixed Price'), ('hourly', 'Hourly Rate')], default='fixed', max_length=10)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('budget_currency', models.CharField(default='USD', max_length=3)),
                ('experience_level', models.CharField(choices=[('any', 'Any Level'), ('beginner', 'Beginner'), ('experienced', 'Experienced'), ('expert', 'Expert')], default='any', max_length=20)),
                ('special_requirements', models.TextField(blank=True)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('applications_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Icon name for UI', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Job Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='JobImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='job_images/%Y/%m/%d/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='users.job')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='job',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='users.jobcategory'),
        ),
        migrations.AddField(
            model_name='job',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['status', 'created_at'], name='users_job_status_ecf1a5_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['category', 'status'], name='users_job_categor_aa768d_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['city', 'status'], name='users_job_city_548548_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['urgent', 'status'], name='users_job_urgent_90453a_idx'),
        ),
    ]
