# Generated by Django 4.2.21 on 2025-05-25 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_add_job_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, help_text='Proposed price for the job', max_digits=10)),
                ('availability', models.CharField(help_text='When can you start/your availability', max_length=200)),
                ('proposal', models.TextField(help_text='Your proposal/cover letter')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('response_at', models.DateTimeField(blank=True, help_text='When client responded', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='users.job')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='work_samples/%Y/%m/%d/')),
                ('title', models.CharField(help_text='Sample title', max_length=200)),
                ('description', models.CharField(blank=True, help_text='Sample description', max_length=500)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_samples', to='users.bid')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='BidDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='bid_documents/%Y/%m/%d/')),
                ('name', models.CharField(help_text='Document name/title', max_length=200)),
                ('description', models.CharField(blank=True, help_text='Document description', max_length=500)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='users.bid')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['job', 'status'], name='users_bid_job_id_f14143_idx'),
        ),
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['worker', 'status'], name='users_bid_worker__39b0c3_idx'),
        ),
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['status', 'submitted_at'], name='users_bid_status_883df4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bid',
            unique_together={('job', 'worker')},
        ),
    ]
