# Generated by Django 4.2.21 on 2025-05-25 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_bid_worksample_biddocument_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
